import 'bootstrap/dist/css/bootstrap.min.css';
import NavbarComponent from '@/components/navbar/navbar-component'
import Container from 'react-bootstrap/Container';
import '../styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavbarComponent />
      {children}
      </body>
    </html>
  )
}
